// Generated generated by .\scripts\generate-works-js.py DO NOT EDIT
createWork({
	name: 'mita',
	description: 'Mita is a simple terminal program to manage tasks.',
	reference: 'https://api.github.com/repos/Nathan2801/mita',
});
createWork({
	name: 'tileless',
	description: 'A general tile manager backend library, for tiling window managers, split views, and related.',
	reference: 'https://api.github.com/repos/Nathan2801/tileless',
});
createWork({
	name: 'chexs',
	description: 'Chess, puzzle and hexagons.',
	reference: 'https://api.github.com/repos/Nathan2801/chexs',
});
createWork({
	name: 'f.js',
	description: 'A functional JavaScript library? Framework? Whatever...',
	reference: 'https://api.github.com/repos/Nathan2801/f.js',
});
createWork({
	name: 'lua-bird',
	description: 'A Flappy Bird clone written in Lua with LÖVE.',
	reference: 'https://api.github.com/repos/Nathan2801/lua-bird',
});
createWork({
	name: 'gamedev.js-2025',
	description: 'A Game Developed for the Gamedev.js 2025. The theme is "Balance".',
	reference: 'https://api.github.com/repos/Nathan2801/gamedev.js-2025',
});
createWork({
	name: 'auto-wordle',
	description: 'A bot that plays wordle',
	reference: 'https://api.github.com/repos/Nathan2801/auto-wordle',
});
createWork({
	name: 'elmor',
	description: 'A Color Selector Written in Elm',
	reference: 'https://api.github.com/repos/Nathan2801/elmor',
});
createWork({
	name: 'arena.h',
	description: 'This is a simple implementation of an arena allocator in C.',
	reference: 'https://api.github.com/repos/Nathan2801/arena.h',
});
