import sys
import json
import urllib3

# This has a weird design because treesitter mess up identation when using
# simple strings containing "[name of function][parent]", it thinks is a python
# function.
def js_project_template(name, desc, link):
    fields = []
    fields.append(f"\tname: {repr(name)},\n")
    fields.append(f"\tdescription: {repr(desc)},\n")
    fields.append(f"\treference: {repr(link)},\n")
    return f"createWork({{\n{"".join(fields)}}});\n"

ignore = [
        "Nathan2801.github.io",
        "project-euler",
        "stream-overlays",
        "avp",
        "aoc2024",
        "rpg-dne",
        "dotfiles",
        "rope",
        ]

username = "Nathan2801"
endpoint = f"https://api.github.com/users/{username}/repos?sort=updated"

response = urllib3.request("GET", endpoint)
assert response.status == 200

generated_js = ""

data = json.loads(response.data)
for repo in data:
    name = repo["name"]
    link = repo["html_url"]
    desc = repo["description"]
    if name in ignore:
        continue
    generated_js += js_project_template(name, desc, link)

output_file = ""
if len(sys.argv) > 1:
    output_file = sys.argv[1]

if output_file == "":
    # End is "" beucase new line is already added for each js_project_template
    # call.
    print(generated_js, end="")
else:
    with open(output_file, "w") as file:
        program_name = sys.argv[0]
        file.write(f"// Generated generated by {program_name} DO NOT EDIT\n")
        file.write(generated_js)
    print(f"Generated javascript was written to {output_file}")
